# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1957de70f6593b03988fd5b1fb875aff16020429d5dfe84e4b999fbcdf6a1ff4e0b8b1ce338219db7f6f6b578bf9e75f47db22d0c9536c3c54fa9a2fbe38fc53

test:
  secret_key_base: 4fd198579d9b00a3881092ffc766d7062bceeda6ab57161f63f5d3c540a108dc359a802e119091c1603bd2bc0895f2997ca1a8629256c23992e3de87c680cd5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
